
## Some of my publications

Get a few overview on my [Google scholar profile](https://scholar.google.com/citations?user=AK4Iq3YAAAAJ&hl=en&oi=ao) or [ORCiD](https://orcid.org/0000-0002-1561-078X). 

Geest, Geert van, Peter M Bourke, Roeland E Voorrips, Agnieszka Marasek-Ciolakowska, Yanlin Liao, Aike Post, Uulke van Meeteren, Richard GF Visser, Chris Maliepaard, and Paul Arens. **An Ultra-Dense Integrated Linkage Map for Hexaploid Chrysanthemum Enables Multi-Allelic QTL Analysis.** Theoretical and Applied Genetics 130 (2017): 2527–41.

Bourke, Peter M, Geert Van Geest, Roeland E Voorrips, Johannes Jansen, Twan Kranenburg, Arwa Shahin, Richard GF Visser, Paul Arens, Marinus JM Smulders, and Chris Maliepaard. **polymapR—Linkage Analysis and Genetic Map Construction from F1 Populations of Outcrossing Polyploids.** Bioinformatics 34, no. 20 (2018): 3496–3502.

Geest, Geert van, Roeland E Voorrips, Danny Esselink, Aike Post, Richard GF Visser, and Paul Arens. **Conclusive Evidence for Hexasomic Inheritance in Chrysanthemum Based on Analysis of a 183 k SNP Array.** BMC Genomics 18 (2017): 1–12.

Barreto de Albuquerque, Juliana, Lukas M Altenburger, Jun Abe, Diego von Werdt, Stefanie Wissmann, Jose Martínez Magdaleno, David Francisco, et al. **Microbial Uptake in Oral Mucosa–Draining Lymph Nodes Leads to Rapid Release of Cytotoxic CD8+ T Cells Lacking a Gut-Homing Phenotype.** Science Immunology 7, no. 72 (2022): eabf1861.

Deng, Haibin, Yanyun Gao, Verdiana Trappetti, Damian Hertig, Darya Karatkevich, Tereza Losmanova, Christian Urzi, et al. **Targeting Lactate Dehydrogenase B-Dependent Mitochondrial Metabolism Affects Tumor Initiating Cells and Inhibits Tumorigenesis of Non-Small Cell Lung Cancer by Inducing mtDNA Damage.** Cellular and Molecular Life Sciences 79, no. 8 (2022): 445.

Walter, Justin D, Melanie Scherer, Cedric AJ Hutter, Alisa A Garaeva, Iwan Zimmermann, Marianne Wyss, Jan Rheinberger, et al. **Biparatopic Sybodies Neutralize SARS-CoV-2 Variants of Concern and Mitigate Drug Resistance.** EMBO Reports 23, no. 4 (2022): e54199.


